on:
  workflow_dispatch:
  push:


jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Build Docker Image
        run: |
          docker build -f docker/Dockerfile .

  build-deb-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Build Debian amd64 Package
        run: agent_packages/resolver/debian/build-package.sh
   
  execute-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: '3.12'

      - name: Install packages
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Execute Unit Tests
        run: python -m unittest discover -v -p *_test.py -s ${{ github.workspace }}/tests

  docs-manual-build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Build PDF Manual
        uses: xu-cheng/latex-action@f1ca82cbed861b3534e2997dd584944f55b884ed
        with:
          root_file: manual/cxone-flow.tex
          work_in_root_file_dir: true

  docs-release-notes-build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Build PDF Release Notes
        uses: xu-cheng/latex-action@f1ca82cbed861b3534e2997dd584944f55b884ed
        with:
          root_file: release_notes/release_notes.tex
          work_in_root_file_dir: true
