name: Publish a Release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x.x'
        required: true
        type: string
      prerelease:
        description: 'Check if this is to publish a pre-release.'
        required: true
        type: boolean
  
permissions:
  contents: read

jobs:
  tag-repo:
    runs-on: cx-public-ubuntu-x64
    outputs:
      tag: ${{ steps.tag-string.outputs.tag }}
      whl_tag: ${{ steps.tag-string.outputs.whl_tag }}
    permissions:
      contents: write
    steps:
      - name: Create tag
        id: tag-string
        run: |
          [ ${{ inputs.prerelease }} = false ] && export TAG=${{ inputs.version }} || \
            export TAG=${{ inputs.version }}-${{ github.run_number }}-prerelease

          [ ${{ inputs.prerelease }} = false ] && export WHL_TAG=${{ inputs.version }} || \
            export WHL_TAG=${{ inputs.version }}rc${{ github.run_number }}

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "whl_tag=$WHL_TAG" >> $GITHUB_OUTPUT

      - name: Validate no tag
        run: |
          git clone --branch ${{ steps.tag-string.outputs.tag }} --depth=1 GITHUB_SERVER_URL/$GITHUB_REPOSITORY > /dev/null 2>&1 && exit 1

      - name: Set Tag
        run: |
          git tag '${{ steps.tag-string.outputs.tag }}'
          git push origin '${{ steps.tag-string.outputs.tag }}'

  force-fail:
    runs-on: cx-public-ubuntu-x64
    needs: [tag-repo]
    steps:
      - name: Delay fails
        run: |
          sleep 90
          exit 1

      
  # validate-no-tag:
  #   runs-on: cx-public-ubuntu-x64
  #   needs: [make-tag-string]
  #   steps:
  #     - name: Fetch Code
  #       continue-on-error: true
  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
  #       with:
  #         ref: refs/tags/${{ needs.make-tag-string.outputs.tag }}
  #     - name: Fail if tag ${{ needs.make-tag-string.outputs.tag }} exists
  #       run: |
  #         [[ $(git describe --tags) ==  ${{ needs.make-tag-string.outputs.tag }} ]] && exit 1 || :

  # invoke-build-for-publish:
  #   uses: ./.github/workflows/invoke-build.yml
  #   with:
  #     tag: ${{ needs.make-tag-string.outputs.tag }}
  #     whl_tag: ${{ needs.make-tag-string.outputs.whl_tag }}
  #     prerelease: ${{ inputs.prerelease }}
  #   secrets:
  #     PACKAGE_USER: ${{ secrets.PACKAGE_USER }}
  #     PACKAGE_PAT: ${{ secrets.PACKAGE_PAT }}
  #   needs: [make-tag-string, validate-no-tag]

  remove-tag-on-failure:
    needs: [tag-repo, force-fail]
    permissions:
      contents: write
    runs-on: cx-public-ubuntu-x64
    if: (failure() || cancelled()) && needs.tag-repo.result == 'success'
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Remove tag
        run: git push origin ':refs/tags/${{ needs.tag-repo.outputs.tag }}'