name: Publish a Release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x.x'
        required: true
        type: string
      prerelease:
        description: 'Check if this is to publish a pre-release.'
        required: true
        type: boolean
env:
  PACKAGE_NAME: cxone/cxone-flow
  DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/cxone/cxone-flow


permissions:
  contents: read

jobs:
  tag-repo:
    runs-on: cx-public-ubuntu-x64
    outputs:
      tag: ${{ steps.tag-string.outputs.tag }}
      whl_tag: ${{ steps.tag-string.outputs.whl_tag }}
    permissions:
      contents: write
    steps:
      - name: Create tag
        id: tag-string
        run: |
          [ ${{ inputs.prerelease }} = false ] && export TAG=${{ inputs.version }} || \
            export TAG=${{ inputs.version }}-${{ github.run_number }}-prerelease

          [ ${{ inputs.prerelease }} = false ] && export WHL_TAG=${{ inputs.version }} || \
            export WHL_TAG=${{ inputs.version }}rc${{ github.run_number }}

          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "whl_tag=$WHL_TAG" >> $GITHUB_OUTPUT

      - name: Validate no tag
        run: |
          set +e
          git clone --branch ${{ steps.tag-string.outputs.tag }} --depth=1 GITHUB_SERVER_URL/$GITHUB_REPOSITORY > /dev/null 2>&1 && exit 1
          set -e

      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set Tag
        run: |
          git tag '${{ steps.tag-string.outputs.tag }}'
          git push origin '${{ steps.tag-string.outputs.tag }}'
  
  publish-tagged-container:
    runs-on: cx-public-ubuntu-x64
    needs: [tag-repo]
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0

      - name: Login to GitHub Container Registry
        uses: step-security/docker-login-action@870af644803bf9f204aed474adbad2958fec048b # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Code @ tag ${{ needs.tag-repo.outputs.tag }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ needs.tag-repo.outputs.tag }}

      - name: Update version.txt
        run: |
            echo __version__=\"${{ needs.tag-repo.outputs.tag }}\" > _version.py

      - name: Build and Push Docker Image
        run: |
          docker build --progress plain -f docker/Dockerfile -t $DOCKER_REPO:${{ needs.tag-repo.outputs.tag }} .
          docker push $DOCKER_REPO:${{ needs.tag-repo.outputs.tag }}

  tag-container-as-latest:
    runs-on: cx-public-ubuntu-x64
    needs: [tag-repo, wait-for-important-steps]
    if: ${{! ${{ inputs.prerelease }} }}
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: step-security/docker-login-action@870af644803bf9f204aed474adbad2958fec048b # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag latest
        run: |
          docker pull $DOCKER_REPO:${{ needs.tag-repo.outputs.tag }}
          docker tag $DOCKER_REPO:${{ needs.tag-repo.outputs.tag }} $DOCKER_REPO:latest
          # docker push $DOCKER_REPO:latest

      
  force-fail:
    runs-on: cx-public-ubuntu-x64
    needs: [tag-repo, publish-tagged-container]
    steps:
      - name: Sleep and fail
        run: sleep 90 && exit 1


  wait-for-important-steps:
    runs-on: cx-public-ubuntu-x64
    needs: [force-fail, publish-tagged-container]
    steps:
      - name: Dummy
        run: exit 0


  unpublish-container-on-failure:
    runs-on: cx-public-ubuntu-x64
    needs: [tag-repo, wait-for-important-steps]
    if: (failure() || cancelled()) && needs.publish-tagged-container.result == 'success'
    permissions:
      packages: delete
    steps:
      - name: Remove published container
        run: gh pkg delete $PACKAGE_NAME --version ${{ needs.tag-repo.outputs.tag }} --repo $GITHUB_REPOSITORY --confirm



  # invoke-build-for-publish:
  #   uses: ./.github/workflows/invoke-build.yml
  #   with:
  #     tag: ${{ needs.make-tag-string.outputs.tag }}
  #     whl_tag: ${{ needs.make-tag-string.outputs.whl_tag }}
  #     prerelease: ${{ inputs.prerelease }}
  #   secrets:
  #     PACKAGE_USER: ${{ secrets.PACKAGE_USER }}
  #     PACKAGE_PAT: ${{ secrets.PACKAGE_PAT }}
  #   needs: [make-tag-string, validate-no-tag]

  remove-tag-on-failure:
    needs: [tag-repo, publish-tagged-container]
    permissions:
      contents: write
    runs-on: cx-public-ubuntu-x64
    if: (failure() || cancelled()) && needs.tag-repo.result == 'success'
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Remove tag
        run: git push origin ':refs/tags/${{ needs.tag-repo.outputs.tag }}'